

## Project 

# creating database on the bases of ER diagram

create database project1;

use project1;

create table categories
(cateogory_id int primary key,
category_name varchar(200));

select * from categories;

-- import data

#procdure for importing/inserting information/data

-- click on the table then right click on categories table imprt data wirzard browse path 

create table brand
(brand_id int primary key,
brand_name varchar(200)); 

select * from brand;

create table products
(product_id int primary key,
product_name varchar(200),
brand_id int,
cateogory_id int,
model_year int,
list_price decimal(10,2),
foreign key(brand_id) references brand(brand_id) on delete cascade on update cascade,
foreign key(cateogory_id) references categories(cateogory_id) on delete cascade on update cascade);

select * from products;

create table customers
(customer_id int primary key,
first_name varchar(200),
last_name varchar(200),
phone varchar(100),
email varchar(200),
street varchar(200),
city varchar(100),
state varchar(50),
zip_code varchar(10));

select * from customers;

create table stores
(store_id int primary key,
store_name varchar(50),
phone varchar(100),
email varchar(100),
street varchar(100),
city varchar(100),
state varchar(50),
zip_code varchar(30));

select * from stores;

create table staffs
(staff_id int primary key,
first_name varchar(200),
last_name varchar(200),
email varchar(100),
phone varchar(100),
`active` int,
store_id int,
manager_id int,
foreign key(store_id) references stores(store_id) on delete cascade on update cascade);

select * from staffs;

create table orders
(order_id int primary key,
customer_id int,
order_status int,
oder_date date,
required_date date,
shipped_date date,
store_id int,
staff_id int,
foreign key(store_id) references stores(store_id) on delete cascade on update cascade,
foreign key(staff_id) references staffs(staff_id) on delete cascade on update cascade);

alter table orders
add constraint fk_customer_id
foreign key(customer_id) references customers(customer_id);

select * from orders; 


create table order_items
(order_id int,
item_id int,
product_id int,
quantity int,
list_price decimal(10,2),
discount decimal(4,2),
foreign key(order_id) references orders(order_id) on delete cascade on update cascade,
foreign key(product_id) references products(product_id) on delete cascade on update cascade);

select * from order_items;

create table stocks
(store_id int,
product_id int,
quantity int,
foreign key(store_id) references stores(store_id) on delete cascade on update cascade,
foreign key(product_id)references products(product_id) on delete cascade on update cascade);

select * from stocks;

# Sales Analysis 

# Calculate total revenue generated by each store. 

select sum(list_price) from products as P
inner join stocks as S
on P.product_id = S.product_id
inner join orders as O
on S.store_id = O.store_id; -- 1414109.76

select sum(list_price) from products; -- 488109.84

select * from stores; --
select * from orders; -- connected on the bases of store_id
select * from products; --
select * from stocks; -- connected on the bases of store_id and product_id


# • Identify top 5 best-selling products. 





 