use project1;

select * from stores; 
select * from orders; 
select * from products; 
select * from stocks;
select * from brand;
select * from categories;
select * from customers;
select * from order_items;
select * from staffs;

-- 3. Functional Requirements (Task to do): 
-- 3.1 Sales Analysis 

-- • Calculate total revenue generated by each store.
-- store -- order_items -- order 

select * from stores;
select * from order_items;
select * from orders;

select store_name ,sum(list_price) from order_items as OI
left join orders as O
on OI.order_id = O.order_id
left join stores as S
on s.store_id = O.store_id
group by store_name; 

-- santa cruz bikes = 11911373.67 , baldwin bikes = 3894954.72 , rowlett bikes = 640078.18

-- • Identify top 5 best-selling products.  
-- products -- order_items -- orders
select * from products;
select * from brand;
select * from categories;
select * from order_items;

select product_name , brand_name , category_name , sum(quantity) as total_sold from products as P
left join brand as B
on b.brand_id = P.brand_id
left join categories as C
on C.cateogory_id = P.cateogory_id
left join order_items as OI
on P.product_id = OI.product_id
group by product_name , brand_name , category_name
order by total_sold desc limit 5; 

-- • Calculate monthly sales trends to observe seasonality and growth. 

select date_format(oder_date , "%Y-%m") as `month`,
sum(list_price * quantity) as total_sales
from orders as O
left join order_items as OI
on O.order_id = OI.order_id
group by `month`
order by `month`; 

-- • Identify Top-Selling Product per Category 
-- product -- category

select * from products;
select * from categories;
select * from order_items;

select category_name , product_name , sum(quantity) as total_quantity from order_items as OI
join products as P
on OI.product_id = P.product_id
join categories as C
on P.cateogory_id = C.cateogory_id
group by category_name , product_name; 
 
with sales as (
select category_name , product_name , sum(quantity) as total_quantity from order_items as OI
join products as P
on OI.product_id = P.product_id
join categories as C
on P.cateogory_id = C.cateogory_id
group by category_name , product_name) ,
rank_products as (
select category_name , product_name , total_quantity, 
rank()over(partition by category_name order by total_quantity desc) as ranking from sales)
select category_name,product_name,total_quantity from rank_products
where ranking = 1 order by category_name;

-- • List of Products with Running Total of daily Sales 
-- product -- orders -- order_items
-- forumla for sales :- total_sales = quantity * list_price *(1-discount)
select * from products;
select * from orders;
select * from order_items;

select p.product_id ,p.product_name ,o.oder_date ,sum(oi.quantity * oi.list_price *(1-oi.discount)) as daily_sales from order_items as OI
left join orders as O
on OI.order_id = O.order_id
left join products as P
on OI.product_id = P.product_id 
group by product_id , product_name , oder_date;

select product_name , oder_date , daily_sales ,
sum(daily_sales) over(partition by product_id order by oder_date) as running_total from (
select p.product_id ,p.product_name ,o.oder_date ,sum(oi.quantity * oi.list_price *(1-oi.discount)) as daily_sales from order_items as OI
left join orders as O
on OI.order_id = O.order_id
left join products as P
on OI.product_id = P.product_id 
group by product_id , product_name , oder_date) as sales_summary
order by product_name , oder_date; 

-- 3.2 Customer Analysis 
-- • Identify customers with the highest purchases. 
-- total purchase 
-- order_items -- orders -- customers

select * from customers;
select * from orders;
select * from order_items;

select c.customer_id , concat(first_name , last_name) as customer_name , sum(quantity * list_price) as total_purchase  from customers as C
left join orders as O
on c.customer_id = o.customer_id
left join order_items as OI
on o.order_id = oi.order_id
group by c.customer_id , customer_name
order by total_purchase desc; 

-- • Find customers who have not placed any orders. 
-- order_items , orders , customers
select * from customers;
select * from orders;
select * from order_items;

select first_name ,last_name ,sum(quantity) as Total_quantity from customers C
join orders as O
on c.customer_id = o.customer_id
join order_items as Oi
on o.order_id = oi.order_id
group by first_name , last_name 
order by total_quantity;
-- there are no customer who have not placed orders.

-- • Identify customers who have placed at least 3 orders and spent more than $ 25,000. 

select * from customers;
select * from orders;
select * from order_items;

select first_name ,last_name ,sum(quantity * list_price) as Total , count(o.order_id) as total_orders from customers C
join orders as O
on c.customer_id = o.customer_id
join order_items as Oi
on o.order_id = oi.order_id
group by first_name , last_name 
having total_orders >=3 and total > 25000
order by total desc; 

-- 3.3 Inventory Management

-- • Identify low-stock products (below 50 items in inventory).

select * from stocks;
select * from products;

select * from stocks as S
left join products as P
on s.product_id = p.product_id
where quantity <= 50 
order by quantity desc; 

-- 3.4 Employee Performance Analysis
-- • Identify the top 5 employees based on order transactions handled. 

select * from orders;
select * from staffs;

select  o.staff_id , first_name , last_name , count(oder_date) as total_orders from staffs as S
left join orders as o
on s.staff_id = o.staff_id
group by o.staff_id , first_name , last_name
order by total_orders desc limit 5; 

-- • Identify staff members with the highest number of orders processed.

-- orders -- staffs
select * from orders;
select * from staffs; 

select  o.staff_id , first_name , last_name , count(oder_date) as total_orders from staffs as S
left join orders as o
on s.staff_id = o.staff_id
group by o.staff_id , first_name , last_name
order by total_orders desc; 

-- • Rank Staff Based on Revenue Generated. 

-- staff order_items order 
-- revenue generate formula = sum(quantity * price *91-discount))

select * from staffs;
select * from order_items;
select * from orders;

select s.staff_id ,s.first_name ,s.last_name ,sum(oi.quantity * oi.list_price *(1 - oi.discount)) as total_revenue from staffs as s
left join orders as O
on s.staff_id = O.staff_id
left join order_items as OI
on o.order_id = OI.order_id
group by s.staff_id ,s.first_name ,s.last_name
order by total_revenue desc; 

with ranking_staff as (
select s.staff_id ,s.first_name ,s.last_name ,sum(oi.quantity * oi.list_price *(1 - oi.discount)) as total_revenue from staffs as s
left join orders as O
on s.staff_id = O.staff_id
left join order_items as OI
on o.order_id = OI.order_id
group by s.staff_id ,s.first_name ,s.last_name)

select staff_id , first_name , last_name , total_revenue,
rank() over(order by total_revenue desc) as revenue_ranking from ranking_staff
order by revenue_ranking;

-- 3.5 Advanced Reporting 
 -- • Rank products by sales volume. 
 -- sales volume = sales quantity
 
 select * from products;
 select * from stocks;
 
 select p.product_id , p.product_name , sum(quantity) as total_quantity from products as P
 left join stocks as S
 on P.product_id = S.product_id
 group by p.product_id , p.product_name;
 
 with sales_volume as(
 select p.product_id , p.product_name , sum(quantity) as total_quantity from products as P
 left join stocks as S
 on P.product_id = S.product_id
 group by p.product_id , p.product_name)
 
 select product_id , product_name , total_quantity ,
 dense_rank() over(order by total_quantity desc) as product_ranking from sales_volume
 order by product_ranking; 
 
 -- • Compare Monthly Sales with Previous Month. 
 
 select * from orders;
 select * from order_items;
 
 select date_format(o.oder_date , "%Y-%M") as month,
 sum(oi.quantity *oi.list_price * (1 - oi.discount)) as total_sales from order_items as OI
 left join orders as O
 on oi.order_id = o.order_id
 group by date_format(o.oder_date , "%Y-%M");
 
 with montly_sales as(
 select date_format(o.oder_date , "%Y-%M") as `month`,
 sum(oi.quantity *oi.list_price * (1 - oi.discount)) as total_sales from order_items as OI
 left join orders as O
 on oi.order_id = o.order_id
 group by date_format(o.oder_date , "%Y-%M"))
 
 select `month` , total_sales , 
 lag(total_sales) over(order by `month`) as previous_month_sales ,
 total_sales - lag(total_sales) over(order by `month`) as diffrence
 from montly_sales
 order by `month`; 
 
 -- • Assign Row Number to Orders by Each Customer. 
 
 select * from orders;
 select * from customers;
 
 select c.customer_id , first_name , last_name , o.oder_date , row_number() over(partition by c.customer_id order by o.oder_date) as order_number 
 from orders as O
 left join customers as C
 on o.customer_id = c.customer_id
 group by c.customer_id , first_name , last_name , o.oder_date
 order by customer_id; 
 
 s
 
